export interface Product {
  id: string;
  name: string;
  category: string;
  categoryKey: string;
  price: number;
  originalPrice?: number;
  discount?: number;
  description: string;
  image: string;
  featured: boolean;
  badge?: string;
  badgeKey?: string;
  nameKey: string;
  descKey: string;
  specifications?: Record<string, string>;
}

export const products: Product[] = [
  {
    id: "golden-sweet-corn",
    name: "Golden Sweet Corn",
    category: "Sweet Corn",
    categoryKey: "cat.sweetCorn",
    price: 4.99,
    description:
      "Hand-picked at peak sweetness, our Golden Sweet Corn bursts with natural flavor. Perfect for grilling, boiling, or adding to your favorite summer salads.",
    image: "/images/products/golden-sweet-corn.jpg",
    featured: true,
    badge: "Best Seller",
    badgeKey: "badge.bestSeller",
    nameKey: "prod.golden-sweet-corn.name",
    descKey: "prod.golden-sweet-corn.desc",
    specifications: {
      Weight: "500g (4-5 ears)",
      Origin: "California, USA",
      "Growing Method": "Organic",
      "Shelf Life": "5-7 days refrigerated",
      Storage: "Keep refrigerated at 2-4°C",
      Variety: "Golden Bantam",
    },
  },
  {
    id: "heritage-popcorn",
    name: "Heritage Popcorn Kernels",
    category: "Popcorn",
    categoryKey: "cat.popcorn",
    price: 6.49,
    originalPrice: 8.99,
    discount: 28,
    description:
      "Our heritage popcorn kernels pop into fluffy, tender morsels with a rich, buttery flavor. A family favorite for movie nights and gatherings.",
    image: "/images/products/heritage-popcorn.jpg",
    featured: true,
    nameKey: "prod.heritage-popcorn.name",
    descKey: "prod.heritage-popcorn.desc",
    specifications: {
      Weight: "450g",
      Origin: "Iowa, USA",
      "Growing Method": "Non-GMO",
      "Shelf Life": "12 months",
      Storage: "Store in a cool, dry place",
      Variety: "Butterfly Popcorn",
    },
  },
  {
    id: "stone-ground-flour",
    name: "Stone-Ground Corn Flour",
    category: "Corn Flour",
    categoryKey: "cat.cornFlour",
    price: 8.99,
    description:
      "Milled from heritage corn varieties, our stone-ground flour delivers authentic flavor and texture for tortillas, breads, and traditional recipes.",
    image: "/images/products/stone-ground-flour.jpg",
    featured: true,
    badge: "New",
    badgeKey: "badge.new",
    nameKey: "prod.stone-ground-flour.name",
    descKey: "prod.stone-ground-flour.desc",
    specifications: {
      Weight: "1kg",
      Origin: "Oaxaca, Mexico",
      "Growing Method": "Heirloom varieties",
      "Shelf Life": "6 months",
      Storage: "Store in airtight container",
      "Protein Content": "8g per 100g",
      Certification: "USDA Organic",
    },
  },
  {
    id: "baby-corn",
    name: "Tender Baby Corn",
    category: "Sweet Corn",
    categoryKey: "cat.sweetCorn",
    price: 3.49,
    description:
      "Harvested young for maximum tenderness, our baby corn adds a delicate crunch to stir-fries, salads, and Asian-inspired dishes.",
    image: "/images/products/baby-corn.jpg",
    featured: false,
    nameKey: "prod.baby-corn.name",
    descKey: "prod.baby-corn.desc",
    specifications: {
      Weight: "200g",
      Origin: "Thailand",
      "Growing Method": "Pesticide-free",
      "Shelf Life": "10 days refrigerated",
      Storage: "Keep refrigerated",
    },
  },
  {
    id: "blue-corn",
    name: "Heritage Blue Corn",
    category: "Specialty",
    categoryKey: "cat.specialty",
    price: 9.99,
    originalPrice: 13.99,
    discount: 29,
    description:
      "A rare variety with deep indigo kernels, packed with antioxidants and a nutty, earthy flavor. Perfect for artisanal tortillas and polenta.",
    image: "/images/products/blue-corn.jpg",
    featured: false,
    badge: "Limited",
    badgeKey: "badge.limited",
    nameKey: "prod.blue-corn.name",
    descKey: "prod.blue-corn.desc",
    specifications: {
      Weight: "750g",
      Origin: "New Mexico, USA",
      "Growing Method": "Traditional Hopi cultivation",
      "Shelf Life": "8 months",
      Storage: "Store in cool, dry place",
      "Antioxidant Level": "High (anthocyanin-rich)",
    },
  },
  {
    id: "corn-oil",
    name: "Cold-Pressed Corn Oil",
    category: "Oils",
    categoryKey: "cat.oils",
    price: 12.99,
    description:
      "Extracted from premium corn kernels using traditional cold-press methods. Rich in vitamin E with a light, clean taste for cooking and dressings.",
    image: "/images/products/corn-oil.jpg",
    featured: false,
    nameKey: "prod.corn-oil.name",
    descKey: "prod.corn-oil.desc",
    specifications: {
      Volume: "500ml",
      Origin: "Argentina",
      Extraction: "Cold-pressed",
      "Shelf Life": "18 months",
      Storage: "Store away from direct sunlight",
      "Smoke Point": "230°C",
      Certification: "USDA Organic",
    },
  },
  {
    id: "corn-silk-tea",
    name: "Corn Silk Herbal Tea",
    category: "Tea",
    categoryKey: "cat.tea",
    price: 7.49,
    description:
      "Dried corn silk steeped into a soothing, golden tea with subtle sweetness. A traditional wellness brew enjoyed for generations.",
    image: "/images/products/corn-silk-tea.jpg",
    featured: false,
    nameKey: "prod.corn-silk-tea.name",
    descKey: "prod.corn-silk-tea.desc",
    specifications: {
      Weight: "100g (30 tea bags)",
      Origin: "Japan",
      "Growing Method": "Organic",
      "Shelf Life": "24 months",
      Storage: "Store in airtight tin",
      Caffeine: "Caffeine-free",
    },
  },
  {
    id: "grilling-corn",
    name: "Grilling Corn Pack",
    category: "Sweet Corn",
    categoryKey: "cat.sweetCorn",
    price: 11.99,
    description:
      "Six ears of premium sweet corn, selected for the perfect size and sweetness for grilling. Comes with our signature herb butter recipe.",
    image: "/images/products/grilling-corn.jpg",
    featured: false,
    badge: "Seasonal",
    badgeKey: "badge.seasonal",
    nameKey: "prod.grilling-corn.name",
    descKey: "prod.grilling-corn.desc",
    specifications: {
      Weight: "1.5kg (6 ears)",
      Origin: "Florida, USA",
      "Growing Method": "Farm-fresh",
      "Shelf Life": "5 days",
      Storage: "Keep refrigerated until grilling",
      Variety: "Silver Queen",
    },
  },
  {
    id: "corn-on-the-cob-pack",
    name: "Fresh Corn on the Cob",
    category: "Sweet Corn",
    categoryKey: "cat.sweetCorn",
    price: 5.99,
    originalPrice: 7.99,
    discount: 25,
    description:
      "Farm-fresh ears of sweet corn, harvested at peak ripeness. Each ear is hand-selected for size and sweetness. Perfect for boiling, steaming, or microwaving.",
    image: "/images/products/corn-on-the-cob-pack.jpg",
    featured: true,
    badge: "Sale",
    badgeKey: "badge.sale",
    nameKey: "prod.corn-on-the-cob-pack.name",
    descKey: "prod.corn-on-the-cob-pack.desc",
    specifications: {
      Weight: "1kg (4 ears)",
      Origin: "Georgia, USA",
      "Growing Method": "Sustainable farming",
      "Shelf Life": "5-7 days refrigerated",
      Storage: "Keep refrigerated with husks on",
      Variety: "Peaches and Cream",
    },
  },
  {
    id: "organic-corn-kernels",
    name: "Organic Corn Kernels",
    category: "Specialty",
    categoryKey: "cat.specialty",
    price: 6.99,
    description:
      "Certified organic corn kernels, frozen at peak freshness to lock in flavor and nutrition. Ideal for soups, salads, side dishes, and homemade salsa.",
    image: "/images/products/organic-corn-kernels.jpg",
    featured: false,
    nameKey: "prod.organic-corn-kernels.name",
    descKey: "prod.organic-corn-kernels.desc",
    specifications: {
      Weight: "500g (frozen)",
      Origin: "Oregon, USA",
      "Growing Method": "USDA Certified Organic",
      "Shelf Life": "12 months frozen",
      Storage: "Keep frozen at -18°C",
      Certification: "USDA Organic, Non-GMO",
    },
  },
  {
    id: "gourmet-popcorn-tin",
    name: "Gourmet Popcorn Gift Tin",
    category: "Popcorn",
    categoryKey: "cat.popcorn",
    price: 18.99,
    originalPrice: 24.99,
    discount: 24,
    description:
      "A beautiful gift tin filled with three flavors of our premium popcorn: White Cheddar, Caramel Crunch, and Kettle Corn. Perfect for holidays and special occasions.",
    image: "/images/products/gourmet-popcorn-tin.jpg",
    featured: true,
    badge: "Gift",
    badgeKey: "badge.gift",
    nameKey: "prod.gourmet-popcorn-tin.name",
    descKey: "prod.gourmet-popcorn-tin.desc",
    specifications: {
      Weight: "680g (3 flavors)",
      Flavors: "White Cheddar, Caramel Crunch, Kettle Corn",
      Origin: "Vermont, USA",
      "Shelf Life": "2 months",
      Storage: "Store sealed at room temperature",
      Packaging: "Reusable decorative tin",
    },
  },
  {
    id: "corn-starch",
    name: "Pure Corn Starch",
    category: "Corn Flour",
    categoryKey: "cat.cornFlour",
    price: 4.49,
    description:
      "Ultra-fine corn starch for thickening sauces, gravies, and soups. Also essential for baking light and fluffy cakes and cookies.",
    image: "/images/products/corn-starch.jpg",
    featured: false,
    nameKey: "prod.corn-starch.name",
    descKey: "prod.corn-starch.desc",
    specifications: {
      Weight: "500g",
      Origin: "Indiana, USA",
      "Growing Method": "Non-GMO",
      "Shelf Life": "24 months",
      Storage: "Store in cool, dry place",
      Certification: "Non-GMO Project Verified",
    },
  },
  {
    id: "corn-salsa-jar",
    name: "Fire-Roasted Corn Salsa",
    category: "Specialty",
    categoryKey: "cat.specialty",
    price: 8.49,
    originalPrice: 10.99,
    discount: 23,
    description:
      "Smoky fire-roasted corn blended with tomatoes, jalapeños, onions, and cilantro. A bold, chunky salsa that pairs perfectly with chips, tacos, and grilled meats.",
    image: "/images/products/corn-salsa-jar.jpg",
    featured: false,
    badge: "Spicy",
    badgeKey: "badge.spicy",
    nameKey: "prod.corn-salsa-jar.name",
    descKey: "prod.corn-salsa-jar.desc",
    specifications: {
      Weight: "340g (12 oz jar)",
      Origin: "Made in USA",
      "Heat Level": "Medium (3/5)",
      "Shelf Life": "18 months unopened",
      Storage: "Refrigerate after opening",
      Ingredients: "Corn, tomato, jalapeño, onion, cilantro, lime",
    },
  },
  {
    id: "sweet-corn-cobs",
    name: "Honey Sweet Corn Cobs",
    category: "Sweet Corn",
    categoryKey: "cat.sweetCorn",
    price: 7.99,
    description:
      "Naturally sweet corn cobs with a honey-like flavor. Each cob is plump, juicy, and bursting with kernels. A summer BBQ essential.",
    image: "/images/products/sweet-corn-cobs.jpg",
    featured: false,
    nameKey: "prod.sweet-corn-cobs.name",
    descKey: "prod.sweet-corn-cobs.desc",
    specifications: {
      Weight: "1.2kg (5 ears)",
      Origin: "South Carolina, USA",
      "Growing Method": "Farm-fresh, hand-picked",
      "Shelf Life": "5 days refrigerated",
      Storage: "Keep refrigerated",
      Variety: "Honey & Cream Bicolor",
    },
  },
];

export const categories = [
  { key: "all", label: "All" },
  { key: "sweetCorn", label: "Sweet Corn" },
  { key: "popcorn", label: "Popcorn" },
  { key: "cornFlour", label: "Corn Flour" },
  { key: "specialty", label: "Specialty" },
  { key: "oils", label: "Oils" },
  { key: "tea", label: "Tea" },
];
