export interface Recipe {
  id: string;
  title: string;
  titleKey: string;
  description: string;
  descKey: string;
  image: string;
  category: string;
  categoryKey: string;
  cookingTime: string;
  prepTime: string;
  servings: number;
  difficulty: "Easy" | "Medium" | "Hard";
  calories: number;
  rating: number;
  isVegetarian: boolean;
  isHealthy: boolean;
  isNew: boolean;
  isPopular: boolean;
  isChefSpecial: boolean;
  ingredients: string[];
  instructions: string[];
  nutrition: {
    protein: string;
    carbs: string;
    fat: string;
    fiber: string;
  };
  tips: string[];
}

export interface RecipeCategory {
  id: string;
  name: string;
  nameKey: string;
  emoji: string;
  recipes: Recipe[];
}

export const recipeCategories: RecipeCategory[] = [
  {
    id: "street-corn",
    name: "Street Corn",
    nameKey: "rcat.streetCorn",
    emoji: "\ud83c\udf3d",
    recipes: [
      {
        id: "mexican-corn-cup",
        title: "Mexican Corn Cup",
        description: "A vibrant street-style corn cup loaded with creamy mayo, cotija cheese, chili powder, and a squeeze of fresh lime.",
        image: "/images/recipes/mexican-corn-cup.jpg",
        category: "Street Corn",
        titleKey: "recipe.mexican-corn-cup.title",
        descKey: "recipe.mexican-corn-cup.desc",
        categoryKey: "rcat.streetCorn",
        cookingTime: "15 min",
        prepTime: "5 min",
        servings: 4,
        difficulty: "Easy",
        calories: 220,
        rating: 4.8,
        isVegetarian: true,
        isHealthy: false,
        isNew: false,
        isPopular: true,
        isChefSpecial: false,
        ingredients: [
          "4 cups corn kernels (fresh or frozen)",
          "3 tablespoons mayonnaise",
          "3 tablespoons Mexican crema or sour cream",
          "1 cup cotija cheese, crumbled",
          "2 teaspoons chili powder (Tajín preferred)",
          "2 tablespoons fresh lime juice",
          "1/4 cup fresh cilantro, chopped",
          "1 serrano pepper, finely diced (optional)",
          "Salt to taste",
          "Lime wedges for serving",
        ],
        instructions: [
          "If using frozen corn, thaw and pat dry. Heat a large skillet over high heat and char the corn kernels for 3–4 minutes until they develop golden-brown spots. Stir occasionally.",
          "In a large bowl, combine the charred corn with mayonnaise, Mexican crema, and lime juice. Mix until the corn is evenly coated.",
          "Fold in the crumbled cotija cheese, reserving some for topping. Add the diced serrano pepper if using.",
          "Season with chili powder and salt to taste. Stir to combine all the flavors.",
          "Divide the corn mixture into cups or small bowls. Top with reserved cotija cheese, extra chili powder, and chopped cilantro.",
          "Serve immediately with lime wedges on the side. Enjoy while warm.",
        ],
        nutrition: {
          protein: "8g",
          carbs: "28g",
          fat: "12g",
          fiber: "3g",
        },
        tips: [
          "Charring the corn in a cast-iron skillet gives the best smoky flavor.",
          "For extra heat, add a dash of hot sauce or cayenne pepper.",
          "Use Tajín seasoning instead of plain chili powder for authentic flavor.",
        ],
      },
      {
        id: "elote",
        title: "Elote",
        description: "Traditional Mexican grilled corn on the cob, charred to perfection and slathered with crema, cheese, and chili.",
        image: "/images/recipes/elote.jpg",
        category: "Street Corn",
        titleKey: "recipe.elote.title",
        descKey: "recipe.elote.desc",
        categoryKey: "rcat.streetCorn",
        cookingTime: "20 min",
        prepTime: "5 min",
        servings: 4,
        difficulty: "Easy",
        calories: 280,
        rating: 4.9,
        isVegetarian: true,
        isHealthy: false,
        isNew: false,
        isPopular: true,
        isChefSpecial: true,
        ingredients: [
          "4 ears of corn, husked",
          "1/4 cup mayonnaise",
          "1/4 cup Mexican crema",
          "1 cup cotija cheese, finely crumbled",
          "2 teaspoons chili powder or Tajín",
          "2 limes, cut into wedges",
          "Fresh cilantro, chopped",
          "Salt to taste",
        ],
        instructions: [
          "Preheat your grill to medium-high heat (about 400°F/200°C). Clean and oil the grates.",
          "Place the husked corn directly on the grill. Cook for 10–12 minutes, turning every 2–3 minutes, until all sides are charred and kernels are tender.",
          "While the corn grills, mix the mayonnaise and Mexican crema together in a small bowl.",
          "Remove the corn from the grill. Immediately brush each ear generously with the crema mixture, coating all sides.",
          "Sprinkle the cotija cheese over the corn, pressing gently so it adheres to the crema coating.",
          "Dust with chili powder, squeeze fresh lime juice over each ear, and garnish with chopped cilantro.",
          "Serve immediately with extra lime wedges on the side.",
        ],
        nutrition: {
          protein: "10g",
          carbs: "32g",
          fat: "16g",
          fiber: "4g",
        },
        tips: [
          "Soak the corn in water with husks on for 30 minutes before grilling for extra moisture.",
          "If you don't have a grill, use a broiler set to high for similar char results.",
          "Serve with wooden sticks inserted at the base for easy handling.",
        ],
      },
      {
        id: "esquites",
        title: "Esquites",
        description: "Warm corn kernels sauteed with butter, epazote, and serrano peppers, served in a cup with all the classic elote toppings.",
        image: "/images/recipes/esquites.jpg",
        category: "Street Corn",
        titleKey: "recipe.esquites.title",
        descKey: "recipe.esquites.desc",
        categoryKey: "rcat.streetCorn",
        cookingTime: "25 min",
        prepTime: "10 min",
        servings: 6,
        difficulty: "Medium",
        calories: 240,
        rating: 4.7,
        isVegetarian: true,
        isHealthy: false,
        isNew: true,
        isPopular: false,
        isChefSpecial: false,
        ingredients: [
          "6 cups corn kernels (about 6 ears)",
          "3 tablespoons butter",
          "1/2 cup white onion, finely diced",
          "2 cloves garlic, minced",
          "2 serrano peppers, minced",
          "1 sprig fresh epazote (or substitute cilantro)",
          "3 tablespoons mayonnaise",
          "3 tablespoons Mexican crema",
          "1 cup cotija cheese, crumbled",
          "2 teaspoons chili powder",
          "2 tablespoons fresh lime juice",
          "Salt to taste",
        ],
        instructions: [
          "Melt the butter in a large, deep skillet or pot over medium-high heat.",
          "Add the diced onion and cook for 2–3 minutes until translucent. Add the garlic and serrano peppers, cooking for another minute until fragrant.",
          "Add the corn kernels and epazote sprig. Cook for 8–10 minutes, stirring occasionally, until the corn is tender and slightly charred in spots.",
          "Remove from heat and discard the epazote sprig. Let cool slightly for 2 minutes.",
          "Stir in the mayonnaise, Mexican crema, and lime juice until the corn is well coated.",
          "Fold in half the cotija cheese. Season with salt to taste.",
          "Divide into cups. Top each serving with remaining cotija cheese and a generous sprinkle of chili powder.",
          "Serve warm with lime wedges.",
        ],
        nutrition: {
          protein: "8g",
          carbs: "30g",
          fat: "14g",
          fiber: "4g",
        },
        tips: [
          "Fresh epazote adds authentic flavor but cilantro works as a substitute.",
          "For a smokier flavor, char the corn in batches without stirring too often.",
          "Leftovers keep well in the fridge for up to 2 days — reheat gently.",
        ],
      },
      {
        id: "boiled-corn",
        title: "Boiled Corn",
        description: "Simple yet satisfying boiled corn brushed with herb butter and sprinkled with sea salt and fresh herbs.",
        image: "/images/recipes/boiled-corn.jpg",
        category: "Street Corn",
        titleKey: "recipe.boiled-corn.title",
        descKey: "recipe.boiled-corn.desc",
        categoryKey: "rcat.streetCorn",
        cookingTime: "10 min",
        prepTime: "5 min",
        servings: 4,
        difficulty: "Easy",
        calories: 150,
        rating: 4.3,
        isVegetarian: true,
        isHealthy: true,
        isNew: false,
        isPopular: false,
        isChefSpecial: false,
        ingredients: [
          "4 ears of corn, husked",
          "6 cups water",
          "1 tablespoon sugar",
          "1 teaspoon salt",
          "3 tablespoons butter, melted",
          "1 tablespoon fresh parsley, chopped",
          "1 tablespoon fresh chives, chopped",
          "Flaky sea salt",
          "Freshly ground black pepper",
        ],
        instructions: [
          "Bring a large pot of water to a rolling boil. Add the sugar and salt, stirring to dissolve.",
          "Carefully add the husked corn ears to the boiling water. Cover the pot.",
          "Boil for 6–8 minutes until the kernels are tender and bright yellow. Do not overcook.",
          "While the corn boils, mix the melted butter with chopped parsley and chives.",
          "Remove the corn from the water and pat dry with a clean towel.",
          "Brush each ear generously with the herb butter. Season with flaky sea salt and black pepper.",
          "Serve immediately while hot.",
        ],
        nutrition: {
          protein: "5g",
          carbs: "27g",
          fat: "6g",
          fiber: "3g",
        },
        tips: [
          "Adding sugar to the water helps sweeten the corn naturally.",
          "Don't boil for more than 8 minutes or the kernels become mushy.",
          "For extra flavor, add a bay leaf and peppercorns to the boiling water.",
        ],
      },
      {
        id: "grilled-corn",
        title: "Grilled Corn",
        description: "Fire-roasted corn with beautiful char marks, basted with garlic butter and finished with fresh parsley.",
        image: "/images/recipes/grilled-corn.jpg",
        category: "Street Corn",
        titleKey: "recipe.grilled-corn.title",
        descKey: "recipe.grilled-corn.desc",
        categoryKey: "rcat.streetCorn",
        cookingTime: "18 min",
        prepTime: "5 min",
        servings: 4,
        difficulty: "Easy",
        calories: 190,
        rating: 4.6,
        isVegetarian: true,
        isHealthy: true,
        isNew: false,
        isPopular: true,
        isChefSpecial: false,
        ingredients: [
          "4 ears of corn, husked",
          "4 tablespoons butter, melted",
          "3 cloves garlic, minced",
          "2 tablespoons fresh parsley, chopped",
          "1 teaspoon smoked paprika",
          "Salt and pepper to taste",
          "Lime wedges for serving",
        ],
        instructions: [
          "Preheat the grill to medium-high heat (400°F/200°C). Clean and oil the grates.",
          "Mix the melted butter with minced garlic, smoked paprika, salt, and pepper.",
          "Place the corn on the grill. Cook for 12–15 minutes, turning every 3 minutes and basting with the garlic butter each time you turn.",
          "The corn is done when all sides have golden char marks and the kernels are tender.",
          "Remove from the grill and brush with any remaining garlic butter.",
          "Sprinkle with fresh parsley and serve with lime wedges.",
        ],
        nutrition: {
          protein: "5g",
          carbs: "29g",
          fat: "9g",
          fiber: "3g",
        },
        tips: [
          "Keep the husks on and pull them back to use as a handle while grilling.",
          "Baste frequently to build up layers of garlic butter flavor.",
          "For a spicy version, add cayenne pepper to the butter mixture.",
        ],
      },
    ],
  },
  {
    id: "popcorn",
    name: "Popcorn",
    nameKey: "rcat.popcorn",
    emoji: "\ud83c\udf7f",
    recipes: [
      {
        id: "butter-popcorn",
        title: "Butter Popcorn",
        description: "Classic movie theater popcorn drenched in rich, golden butter with a touch of salt.",
        image: "/images/recipes/butter-popcorn.jpg",
        category: "Popcorn",
        titleKey: "recipe.butter-popcorn.title",
        descKey: "recipe.butter-popcorn.desc",
        categoryKey: "rcat.popcorn",
        cookingTime: "5 min",
        prepTime: "2 min",
        servings: 4,
        difficulty: "Easy",
        calories: 180,
        rating: 4.5,
        isVegetarian: true,
        isHealthy: false,
        isNew: false,
        isPopular: true,
        isChefSpecial: false,
        ingredients: [
          "1/2 cup popcorn kernels",
          "3 tablespoons coconut oil or vegetable oil",
          "4 tablespoons butter, melted",
          "1 teaspoon fine salt (or popcorn salt)",
        ],
        instructions: [
          "Place the oil and 3 test kernels in a large, heavy-bottomed pot with a lid. Heat over medium-high heat.",
          "When the test kernels pop, add the remaining popcorn kernels in an even layer. Cover with the lid slightly ajar for steam to escape.",
          "Shake the pot gently and continuously as the kernels pop. Remove from heat when popping slows to 2–3 seconds between pops (about 3 minutes).",
          "Immediately transfer the popcorn to a large bowl. Drizzle with melted butter while tossing to coat evenly.",
          "Sprinkle with salt and toss again. Serve immediately.",
        ],
        nutrition: {
          protein: "3g",
          carbs: "18g",
          fat: "12g",
          fiber: "3g",
        },
        tips: [
          "Use clarified butter (ghee) for movie-theater flavor without sogginess.",
          "Shaking the pot prevents burning and ensures even popping.",
          "Season while the popcorn is still hot so the salt sticks.",
        ],
      },
      {
        id: "cheese-popcorn",
        title: "Cheese Popcorn",
        description: "Crunchy popcorn coated in a savory blend of aged cheddar and parmesan cheese powder.",
        image: "/images/recipes/cheese-popcorn.jpg",
        category: "Popcorn",
        titleKey: "recipe.cheese-popcorn.title",
        descKey: "recipe.cheese-popcorn.desc",
        categoryKey: "rcat.popcorn",
        cookingTime: "8 min",
        prepTime: "5 min",
        servings: 4,
        difficulty: "Easy",
        calories: 210,
        rating: 4.6,
        isVegetarian: true,
        isHealthy: false,
        isNew: false,
        isPopular: true,
        isChefSpecial: false,
        ingredients: [
          "1/2 cup popcorn kernels",
          "3 tablespoons oil",
          "1/2 cup cheddar cheese powder",
          "2 tablespoons grated parmesan",
          "1/2 teaspoon garlic powder",
          "1/2 teaspoon onion powder",
          "2 tablespoons butter, melted",
          "Salt to taste",
        ],
        instructions: [
          "Pop the popcorn using your preferred method (stovetop or air popper). Transfer to a large bowl.",
          "Drizzle the melted butter over the popcorn while tossing to coat evenly.",
          "In a small bowl, mix the cheddar cheese powder, parmesan, garlic powder, onion powder, and salt.",
          "Sprinkle the cheese mixture over the popcorn in batches, tossing after each addition to ensure even coating.",
          "Serve immediately for maximum crunch.",
        ],
        nutrition: {
          protein: "7g",
          carbs: "20g",
          fat: "13g",
          fiber: "3g",
        },
        tips: [
          "For best results, use a fine cheese powder — it adheres better than shredded cheese.",
          "Toss in a large paper bag for mess-free, even coating.",
          "Store in an airtight container for up to 2 days.",
        ],
      },
      {
        id: "caramel-popcorn",
        title: "Caramel Popcorn",
        description: "Sweet and crunchy popcorn glazed with homemade caramel, perfect for gifting and snacking.",
        image: "/images/recipes/caramel-popcorn.jpg",
        category: "Popcorn",
        titleKey: "recipe.caramel-popcorn.title",
        descKey: "recipe.caramel-popcorn.desc",
        categoryKey: "rcat.popcorn",
        cookingTime: "30 min",
        prepTime: "10 min",
        servings: 8,
        difficulty: "Medium",
        calories: 290,
        rating: 4.8,
        isVegetarian: true,
        isHealthy: false,
        isNew: false,
        isPopular: true,
        isChefSpecial: true,
        ingredients: [
          "1/2 cup popcorn kernels (makes about 12 cups popped)",
          "1 cup packed brown sugar",
          "1/4 cup corn syrup",
          "1/2 cup butter",
          "1/2 teaspoon salt",
          "1/2 teaspoon baking soda",
          "1 teaspoon vanilla extract",
        ],
        instructions: [
          "Preheat oven to 250°F (120°C). Line a large baking sheet with parchment paper.",
          "Pop the popcorn using your preferred method. Remove any unpopped kernels. Transfer to a very large bowl.",
          "In a medium saucepan, combine brown sugar, corn syrup, butter, and salt. Cook over medium heat, stirring constantly, until the butter melts and the mixture comes to a boil.",
          "Stop stirring and let the caramel boil for 4 minutes without stirring.",
          "Remove from heat. Carefully stir in the baking soda and vanilla — the mixture will foam up.",
          "Immediately pour the hot caramel over the popcorn. Toss with two spoons or spatulas to coat evenly.",
          "Spread the coated popcorn onto the prepared baking sheet in an even layer.",
          "Bake for 1 hour, stirring every 15 minutes to ensure even coating and crunch.",
          "Remove from oven and let cool completely on the baking sheet. Break into clusters and serve.",
        ],
        nutrition: {
          protein: "2g",
          carbs: "45g",
          fat: "12g",
          fiber: "2g",
        },
        tips: [
          "Stirring during baking is crucial — it prevents clumping and ensures each kernel gets coated.",
          "The caramel will crisp up as it cools. Be patient!",
          "Store in an airtight container for up to a week.",
        ],
      },
      {
        id: "chocolate-popcorn",
        title: "Chocolate Popcorn",
        description: "Gourmet popcorn drizzled with dark and white chocolate, finished with a sprinkle of sea salt.",
        image: "/images/recipes/chocolate-popcorn.jpg",
        category: "Popcorn",
        titleKey: "recipe.chocolate-popcorn.title",
        descKey: "recipe.chocolate-popcorn.desc",
        categoryKey: "rcat.popcorn",
        cookingTime: "15 min",
        prepTime: "10 min",
        servings: 6,
        difficulty: "Medium",
        calories: 260,
        rating: 4.7,
        isVegetarian: true,
        isHealthy: false,
        isNew: true,
        isPopular: false,
        isChefSpecial: false,
        ingredients: [
          "1/2 cup popcorn kernels",
          "3 tablespoons oil",
          "4 oz dark chocolate, chopped",
          "3 oz white chocolate, chopped",
          "1 tablespoon coconut oil",
          "Flaky sea salt",
          "Sprinkles or crushed candy canes (optional)",
        ],
        instructions: [
          "Pop the popcorn using your preferred method. Transfer to a large parchment-lined baking sheet.",
          "Melt the dark chocolate with 1/2 tablespoon coconut oil in a microwave-safe bowl in 30-second intervals, stirring between each.",
          "In a separate bowl, melt the white chocolate with the remaining coconut oil using the same method.",
          "Using a fork, drizzle the melted dark chocolate back and forth over the popcorn.",
          "Immediately drizzle the white chocolate in the opposite direction for a marbled effect.",
          "Sprinkle with flaky sea salt and optional toppings while the chocolate is still wet.",
          "Let the chocolate set at room temperature for 20 minutes, or refrigerate for 10 minutes to speed up.",
          "Break into pieces and serve.",
        ],
        nutrition: {
          protein: "4g",
          carbs: "30g",
          fat: "15g",
          fiber: "3g",
        },
        tips: [
          "Temper the chocolate for a glossy finish that snaps when you bite it.",
          "Use high-quality chocolate for the best flavor — it makes a big difference.",
          "This makes a beautiful gift when packaged in cellophane bags.",
        ],
      },
      {
        id: "spicy-popcorn",
        title: "Spicy Popcorn",
        description: "Bold popcorn seasoned with cayenne, paprika, and a hint of cumin for an addictive kick.",
        image: "/images/recipes/spicy-popcorn.jpg",
        category: "Popcorn",
        titleKey: "recipe.spicy-popcorn.title",
        descKey: "recipe.spicy-popcorn.desc",
        categoryKey: "rcat.popcorn",
        cookingTime: "8 min",
        prepTime: "3 min",
        servings: 4,
        difficulty: "Easy",
        calories: 170,
        rating: 4.4,
        isVegetarian: true,
        isHealthy: true,
        isNew: true,
        isPopular: false,
        isChefSpecial: false,
        ingredients: [
          "1/2 cup popcorn kernels",
          "3 tablespoons oil",
          "2 tablespoons butter, melted",
          "1 teaspoon cayenne pepper",
          "1 teaspoon smoked paprika",
          "1/2 teaspoon ground cumin",
          "1/2 teaspoon garlic powder",
          "1/2 teaspoon salt",
          "Lime zest (optional)",
        ],
        instructions: [
          "Pop the popcorn using your preferred method. Transfer to a large bowl.",
          "In a small bowl, combine the cayenne pepper, smoked paprika, cumin, garlic powder, and salt.",
          "Drizzle the melted butter over the popcorn while tossing to coat.",
          "Sprinkle the spice mixture over the popcorn in batches, tossing after each addition.",
          "Add lime zest if using, and toss one final time.",
          "Serve immediately.",
        ],
        nutrition: {
          protein: "3g",
          carbs: "17g",
          fat: "10g",
          fiber: "3g",
        },
        tips: [
          "Adjust the cayenne to your heat preference — start with 1/2 teaspoon if you're sensitive to spice.",
          "For a smoky twist, use chipotle powder instead of cayenne.",
          "A squeeze of fresh lime juice takes this to the next level.",
        ],
      },
    ],
  },
  {
    id: "salads",
    name: "Salads",
    nameKey: "rcat.salads",
    emoji: "\ud83e\udd57",
    recipes: [
      {
        id: "corn-salad",
        title: "Corn Salad",
        description: "Fresh and zesty salad with sweet corn, cherry tomatoes, red onion, and a lime vinaigrette.",
        image: "/images/recipes/corn-salad.jpg",
        category: "Salads",
        titleKey: "recipe.corn-salad.title",
        descKey: "recipe.corn-salad.desc",
        categoryKey: "rcat.salads",
        cookingTime: "15 min",
        prepTime: "10 min",
        servings: 4,
        difficulty: "Easy",
        calories: 180,
        rating: 4.6,
        isVegetarian: true,
        isHealthy: true,
        isNew: false,
        isPopular: true,
        isChefSpecial: false,
        ingredients: [
          "4 cups corn kernels (fresh, grilled, or frozen and thawed)",
          "1 cup cherry tomatoes, halved",
          "1/2 cup red onion, finely diced",
          "1/4 cup fresh cilantro, chopped",
          "1 jalapeño, seeded and minced",
          "3 tablespoons olive oil",
          "2 tablespoons fresh lime juice",
          "1 teaspoon honey",
          "Salt and pepper to taste",
        ],
        instructions: [
          "If using fresh corn, cook in boiling water for 3 minutes, then drain and cool. If using frozen, thaw and pat dry.",
          "In a large bowl, combine the corn, cherry tomatoes, red onion, cilantro, and jalapeño.",
          "In a small bowl, whisk together the olive oil, lime juice, honey, salt, and pepper.",
          "Pour the dressing over the salad and toss gently to combine.",
          "Taste and adjust seasoning. Let sit for 5 minutes to allow flavors to meld.",
          "Serve chilled or at room temperature.",
        ],
        nutrition: {
          protein: "5g",
          carbs: "24g",
          fat: "9g",
          fiber: "4g",
        },
        tips: [
          "Grilling the corn first adds a wonderful smoky depth to the salad.",
          "Make ahead — it tastes even better after marinating for an hour.",
          "Add diced avocado just before serving for extra creaminess.",
        ],
      },
      {
        id: "mexican-salad",
        title: "Mexican Salad",
        description: "A hearty salad with black beans, corn, avocado, jalapeno, and cilantro-lime dressing.",
        image: "/images/recipes/mexican-salad.jpg",
        category: "Salads",
        titleKey: "recipe.mexican-salad.title",
        descKey: "recipe.mexican-salad.desc",
        categoryKey: "rcat.salads",
        cookingTime: "20 min",
        prepTime: "15 min",
        servings: 4,
        difficulty: "Easy",
        calories: 320,
        rating: 4.7,
        isVegetarian: true,
        isHealthy: true,
        isNew: false,
        isPopular: true,
        isChefSpecial: false,
        ingredients: [
          "2 cups romaine lettuce, chopped",
          "1 can (15 oz) black beans, drained and rinsed",
          "2 cups corn kernels",
          "1 cup cherry tomatoes, halved",
          "1 ripe avocado, diced",
          "1/2 cup red bell pepper, diced",
          "1/4 cup red onion, diced",
          "1 jalapeño, seeded and minced",
          "1/4 cup fresh cilantro, chopped",
          "1/2 cup tortilla strips",
          "3 tablespoons olive oil",
          "2 tablespoons lime juice",
          "1 teaspoon cumin",
          "Salt and pepper to taste",
        ],
        instructions: [
          "In a small bowl, whisk together olive oil, lime juice, cumin, salt, and pepper to make the dressing.",
          "In a large bowl, combine the lettuce, black beans, corn, tomatoes, bell pepper, red onion, and jalapeño.",
          "Add the diced avocado and gently toss to combine.",
          "Pour the cilantro-lime dressing over the salad and toss gently.",
          "Top with tortilla strips and extra cilantro.",
          "Serve immediately.",
        ],
        nutrition: {
          protein: "12g",
          carbs: "38g",
          fat: "16g",
          fiber: "10g",
        },
        tips: [
          "Add the avocado last to keep it from getting mushy.",
          "For a protein boost, add grilled chicken or shrimp.",
          "The dressing can be made ahead and stored for up to 3 days.",
        ],
      },
      {
        id: "chicken-corn-salad",
        title: "Chicken Corn Salad",
        description: "Grilled chicken breast tossed with sweet corn, mixed greens, and honey-mustard dressing.",
        image: "/images/recipes/chicken-corn-salad.jpg",
        category: "Salads",
        titleKey: "recipe.chicken-corn-salad.title",
        descKey: "recipe.chicken-corn-salad.desc",
        categoryKey: "rcat.salads",
        cookingTime: "25 min",
        prepTime: "15 min",
        servings: 4,
        difficulty: "Medium",
        calories: 380,
        rating: 4.8,
        isVegetarian: false,
        isHealthy: true,
        isNew: false,
        isPopular: true,
        isChefSpecial: true,
        ingredients: [
          "2 boneless chicken breasts",
          "3 cups corn kernels",
          "6 cups mixed greens",
          "1 cup cherry tomatoes, halved",
          "1/2 cup cucumber, diced",
          "1/4 cup red onion, thinly sliced",
          "1/4 cup crumbled feta cheese",
          "2 tablespoons olive oil",
          "Salt, pepper, and garlic powder for chicken",
          "3 tablespoons olive oil",
          "2 tablespoons honey",
          "1 tablespoon Dijon mustard",
          "1 tablespoon apple cider vinegar",
        ],
        instructions: [
          "Season chicken breasts with salt, pepper, and garlic powder. Grill or pan-sear in 1 tablespoon olive oil for 6–7 minutes per side until cooked through (165°F internal). Let rest 5 minutes, then slice.",
          "In the same pan, add the corn kernels and cook for 3–4 minutes until slightly charred. Set aside.",
          "Make the dressing: whisk together olive oil, honey, Dijon mustard, and apple cider vinegar.",
          "In a large bowl, combine the mixed greens, charred corn, tomatoes, cucumber, and red onion.",
          "Top with sliced grilled chicken and crumbled feta.",
          "Drizzle with honey-mustard dressing and serve.",
        ],
        nutrition: {
          protein: "32g",
          carbs: "28g",
          fat: "18g",
          fiber: "4g",
        },
        tips: [
          "Pound the chicken to even thickness for uniform cooking.",
          "Let the chicken rest before slicing to keep it juicy.",
          "Substitute grilled shrimp for a seafood variation.",
        ],
      },
      {
        id: "avocado-corn-salad",
        title: "Avocado Corn Salad",
        description: "Creamy avocado chunks with charred corn, radish, and a citrus-chili dressing.",
        image: "/images/recipes/avocado-corn-salad.jpg",
        category: "Salads",
        titleKey: "recipe.avocado-corn-salad.title",
        descKey: "recipe.avocado-corn-salad.desc",
        categoryKey: "rcat.salads",
        cookingTime: "15 min",
        prepTime: "10 min",
        servings: 4,
        difficulty: "Easy",
        calories: 290,
        rating: 4.9,
        isVegetarian: true,
        isHealthy: true,
        isNew: true,
        isPopular: false,
        isChefSpecial: false,
        ingredients: [
          "3 cups corn kernels",
          "2 ripe avocados, diced",
          "4 radishes, thinly sliced",
          "1/4 cup red onion, finely diced",
          "1/4 cup fresh cilantro, chopped",
          "1 jalapeño, seeded and minced",
          "2 tablespoons olive oil",
          "2 tablespoons fresh lime juice",
          "1 tablespoon orange juice",
          "1/2 teaspoon chili powder",
          "Salt and pepper to taste",
        ],
        instructions: [
          "Char the corn in a hot skillet with a drizzle of oil for 4–5 minutes. Let cool.",
          "In a large bowl, combine the charred corn, diced avocado, radishes, red onion, cilantro, and jalapeño.",
          "Whisk together olive oil, lime juice, orange juice, chili powder, salt, and pepper.",
          "Pour the dressing over the salad and toss gently — be careful not to mash the avocado.",
          "Serve immediately to keep the avocado from browning.",
        ],
        nutrition: {
          protein: "6g",
          carbs: "26g",
          fat: "20g",
          fiber: "8g",
        },
        tips: [
          "Toss the avocado in lime juice first to prevent browning.",
          "Use ripe but firm avocados so they hold their shape.",
          "This salad is best served fresh — it doesn't keep well.",
        ],
      },
      {
        id: "bean-corn-salad",
        title: "Bean Corn Salad",
        description: "Protein-packed salad with three bean varieties, corn, bell peppers, and a smoky chipotle dressing.",
        image: "/images/recipes/bean-corn-salad.jpg",
        category: "Salads",
        titleKey: "recipe.bean-corn-salad.title",
        descKey: "recipe.bean-corn-salad.desc",
        categoryKey: "rcat.salads",
        cookingTime: "20 min",
        prepTime: "15 min",
        servings: 6,
        difficulty: "Easy",
        calories: 260,
        rating: 4.5,
        isVegetarian: true,
        isHealthy: true,
        isNew: false,
        isPopular: false,
        isChefSpecial: false,
        ingredients: [
          "1 can (15 oz) black beans, drained",
          "1 can (15 oz) kidney beans, drained",
          "1 can (15 oz) chickpeas, drained",
          "2 cups corn kernels",
          "1 red bell pepper, diced",
          "1 green bell pepper, diced",
          "1/2 cup red onion, diced",
          "1/4 cup fresh cilantro",
          "3 tablespoons olive oil",
          "2 tablespoons lime juice",
          "1 chipotle pepper in adobo, minced",
          "1 teaspoon cumin",
          "Salt and pepper to taste",
        ],
        instructions: [
          "In a large bowl, combine the black beans, kidney beans, chickpeas, corn, bell peppers, and red onion.",
          "In a small bowl, whisk together olive oil, lime juice, minced chipotle, cumin, salt, and pepper.",
          "Pour the chipotle dressing over the bean mixture and toss to combine.",
          "Fold in the fresh cilantro.",
          "Cover and refrigerate for at least 30 minutes to let the flavors develop.",
          "Serve chilled as a side dish or light meal.",
        ],
        nutrition: {
          protein: "14g",
          carbs: "35g",
          fat: "8g",
          fiber: "12g",
        },
        tips: [
          "Rinse canned beans thoroughly to reduce sodium by up to 40%.",
          "This salad gets better as it sits — make it a day ahead for maximum flavor.",
          "Add diced mango for a sweet contrast to the smoky chipotle.",
        ],
      },
    ],
  },
  {
    id: "soups",
    name: "Soups",
    nameKey: "rcat.soups",
    emoji: "\ud83c\udf72",
    recipes: [
      {
        id: "cream-corn-soup",
        title: "Cream Corn Soup",
        description: "Velvety smooth soup made with fresh corn, cream, and a touch of truffle oil for luxury.",
        image: "/images/recipes/cream-corn-soup.jpg",
        category: "Soups",
        titleKey: "recipe.cream-corn-soup.title",
        descKey: "recipe.cream-corn-soup.desc",
        categoryKey: "rcat.soups",
        cookingTime: "30 min",
        prepTime: "10 min",
        servings: 4,
        difficulty: "Medium",
        calories: 280,
        rating: 4.8,
        isVegetarian: true,
        isHealthy: false,
        isNew: false,
        isPopular: true,
        isChefSpecial: true,
        ingredients: [
          "6 cups corn kernels (about 6 ears)",
          "2 tablespoons butter",
          "1 medium onion, diced",
          "3 cloves garlic, minced",
          "4 cups vegetable broth",
          "1 cup heavy cream",
          "1/2 teaspoon white pepper",
          "Salt to taste",
          "Truffle oil for drizzling",
          "Fresh chives for garnish",
        ],
        instructions: [
          "Melt the butter in a large pot over medium heat. Add the diced onion and cook for 4–5 minutes until soft and translucent.",
          "Add the garlic and cook for 1 minute until fragrant.",
          "Add the corn kernels and vegetable broth. Bring to a boil, then reduce heat and simmer for 15 minutes until the corn is very tender.",
          "Using an immersion blender, blend the soup until smooth. Alternatively, transfer in batches to a regular blender.",
          "Return the soup to the pot. Stir in the heavy cream and white pepper. Heat gently for 5 minutes — do not boil.",
          "Season with salt to taste. Ladle into bowls and drizzle with truffle oil and garnish with chives.",
        ],
        nutrition: {
          protein: "8g",
          carbs: "32g",
          fat: "16g",
          fiber: "4g",
        },
        tips: [
          "For extra silkiness, strain the blended soup through a fine-mesh sieve.",
          "Save a few whole corn kernels to use as garnish.",
          "Substitute coconut cream for a dairy-free version.",
        ],
      },
      {
        id: "chicken-corn-soup",
        title: "Chicken Corn Soup",
        description: "Hearty soup with tender chicken, sweet corn, and vegetables in a savory broth.",
        image: "/images/recipes/chicken-corn-soup.jpg",
        category: "Soups",
        titleKey: "recipe.chicken-corn-soup.title",
        descKey: "recipe.chicken-corn-soup.desc",
        categoryKey: "rcat.soups",
        cookingTime: "40 min",
        prepTime: "15 min",
        servings: 6,
        difficulty: "Medium",
        calories: 320,
        rating: 4.7,
        isVegetarian: false,
        isHealthy: true,
        isNew: false,
        isPopular: true,
        isChefSpecial: false,
        ingredients: [
          "2 boneless chicken breasts",
          "4 cups corn kernels",
          "6 cups chicken broth",
          "1 large potato, peeled and diced",
          "1 carrot, diced",
          "1 celery stalk, diced",
          "1 small onion, diced",
          "2 cloves garlic, minced",
          "2 tablespoons butter",
          "1/2 cup milk",
          "2 tablespoons cornstarch mixed with 2 tablespoons water",
          "Salt, pepper, and fresh thyme",
        ],
        instructions: [
          "Poach the chicken breasts in simmering water for 20 minutes until cooked through. Remove, let cool, and shred into bite-sized pieces.",
          "In a large pot, melt the butter over medium heat. Sauté the onion, carrot, and celery for 5 minutes.",
          "Add the garlic and cook for 1 minute. Add the potato, corn, and chicken broth.",
          "Bring to a boil, then reduce heat and simmer for 15 minutes until the potato is tender.",
          "Stir in the shredded chicken and milk. Bring back to a gentle simmer.",
          "Slowly pour in the cornstarch slurry while stirring to thicken the soup. Cook for 2 more minutes.",
          "Season with salt, pepper, and fresh thyme. Serve hot.",
        ],
        nutrition: {
          protein: "28g",
          carbs: "34g",
          fat: "10g",
          fiber: "4g",
        },
        tips: [
          "Use a rotisserie chicken to save time on the poaching step.",
          "For a thicker soup, blend half the corn before adding it.",
          "This soup freezes well for up to 3 months.",
        ],
      },
      {
        id: "corn-chowder",
        title: "Corn Chowder",
        description: "Rich and creamy chowder loaded with corn, potatoes, bacon, and fresh thyme.",
        image: "/images/recipes/corn-chowder.jpg",
        category: "Soups",
        titleKey: "recipe.corn-chowder.title",
        descKey: "recipe.corn-chowder.desc",
        categoryKey: "rcat.soups",
        cookingTime: "45 min",
        prepTime: "15 min",
        servings: 6,
        difficulty: "Medium",
        calories: 380,
        rating: 4.9,
        isVegetarian: false,
        isHealthy: false,
        isNew: false,
        isPopular: true,
        isChefSpecial: false,
        ingredients: [
          "6 slices bacon, diced",
          "2 tablespoons butter",
          "1 large onion, diced",
          "2 cloves garlic, minced",
          "1/4 cup all-purpose flour",
          "4 cups chicken broth",
          "4 cups corn kernels",
          "2 large potatoes, peeled and diced",
          "1 cup heavy cream",
          "1 cup whole milk",
          "1 teaspoon fresh thyme leaves",
          "Salt and pepper to taste",
          "Green onions for garnish",
        ],
        instructions: [
          "In a large pot, cook the diced bacon over medium heat until crispy (about 6 minutes). Remove bacon and set aside, leaving the fat in the pot.",
          "Add butter to the bacon fat. Sauté the onion for 4–5 minutes until soft. Add garlic and cook 1 minute.",
          "Sprinkle the flour over the vegetables and stir for 1 minute to cook out the raw flour taste.",
          "Gradually pour in the chicken broth while stirring constantly to prevent lumps.",
          "Add the potatoes and corn. Bring to a boil, then reduce heat and simmer for 15–18 minutes until potatoes are fork-tender.",
          "Stir in the heavy cream, milk, and thyme. Heat through for 5 minutes without boiling.",
          "Season with salt and pepper. Ladle into bowls and top with crispy bacon and green onions.",
        ],
        nutrition: {
          protein: "16g",
          carbs: "42g",
          fat: "20g",
          fiber: "5g",
        },
        tips: [
          "For a thicker chowder, mash some of the potatoes against the side of the pot.",
          "Use fresh corn in summer for the sweetest flavor.",
          "Don't let the chowder boil after adding the cream — it can curdle.",
        ],
      },
      {
        id: "mushroom-corn-soup",
        title: "Mushroom Corn Soup",
        description: "Earthy mushroom and sweet corn combined in a silky soup with a drizzle of herb oil.",
        image: "/images/recipes/mushroom-corn-soup.jpg",
        category: "Soups",
        titleKey: "recipe.mushroom-corn-soup.title",
        descKey: "recipe.mushroom-corn-soup.desc",
        categoryKey: "rcat.soups",
        cookingTime: "35 min",
        prepTime: "10 min",
        servings: 4,
        difficulty: "Medium",
        calories: 250,
        rating: 4.6,
        isVegetarian: true,
        isHealthy: true,
        isNew: true,
        isPopular: false,
        isChefSpecial: false,
        ingredients: [
          "3 cups corn kernels",
          "8 oz cremini mushrooms, sliced",
          "2 tablespoons butter",
          "1 small onion, diced",
          "3 cloves garlic, minced",
          "4 cups vegetable broth",
          "1/2 cup heavy cream",
          "1 tablespoon fresh thyme",
          "Salt and white pepper to taste",
          "2 tablespoons herb oil (olive oil blended with basil and parsley)",
        ],
        instructions: [
          "Melt butter in a large pot over medium-high heat. Add the mushrooms and cook without stirring for 3 minutes to develop a golden sear. Stir and cook 3 more minutes.",
          "Add the onion and cook for 3 minutes. Add the garlic and thyme, cooking 1 minute.",
          "Add the corn and vegetable broth. Bring to a boil, then simmer for 15 minutes.",
          "Blend the soup until smooth using an immersion blender.",
          "Stir in the heavy cream and heat gently for 5 minutes. Season with salt and white pepper.",
          "Ladle into bowls and drizzle with herb oil before serving.",
        ],
        nutrition: {
          protein: "8g",
          carbs: "28g",
          fat: "14g",
          fiber: "5g",
        },
        tips: [
          "Don't crowd the mushrooms — cook them in batches for the best sear.",
          "Use a mix of mushroom varieties for deeper, more complex flavor.",
          "White pepper keeps the soup's color clean and appetizing.",
        ],
      },
    ],
  },
  {
    id: "mexican",
    name: "Mexican",
    nameKey: "rcat.mexican",
    emoji: "\ud83c\udf2e",
    recipes: [
      {
        id: "corn-tacos",
        title: "Tacos",
        description: "Soft corn tortillas filled with seasoned meat, fresh salsa, guacamole, and a squeeze of lime.",
        image: "/images/recipes/corn-tacos.jpg",
        category: "Mexican",
        titleKey: "recipe.corn-tacos.title",
        descKey: "recipe.corn-tacos.desc",
        categoryKey: "rcat.mexican",
        cookingTime: "25 min",
        prepTime: "20 min",
        servings: 4,
        difficulty: "Medium",
        calories: 350,
        rating: 4.9,
        isVegetarian: false,
        isHealthy: false,
        isNew: false,
        isPopular: true,
        isChefSpecial: true,
        ingredients: [
          "1 lb ground beef or chicken",
          "12 small corn tortillas",
          "1 packet taco seasoning (or homemade: cumin, chili powder, paprika, garlic powder, onion powder, oregano, salt, pepper)",
          "1 cup lettuce, shredded",
          "1 cup pico de gallo",
          "1 avocado, sliced",
          "1/2 cup sour cream",
          "1/2 cup cotija cheese, crumbled",
          "Fresh lime wedges",
          "Fresh cilantro",
        ],
        instructions: [
          "Cook the ground meat in a large skillet over medium-high heat, breaking it up, for 8–10 minutes until browned. Drain excess fat.",
          "Add the taco seasoning and 1/4 cup water. Stir and simmer for 5 minutes until the sauce thickens and coats the meat.",
          "Warm the corn tortillas in a dry skillet for 30 seconds per side, or wrap in damp paper towels and microwave for 30 seconds.",
          "Assemble the tacos: place seasoned meat on each tortilla, then top with shredded lettuce, pico de gallo, avocado slices, and cotija cheese.",
          "Add a dollop of sour cream, fresh cilantro, and a squeeze of lime juice.",
          "Serve immediately with extra lime wedges on the side.",
        ],
        nutrition: {
          protein: "22g",
          carbs: "30g",
          fat: "16g",
          fiber: "5g",
        },
        tips: [
          "Double-stack tortillas for sturdier tacos that won't fall apart.",
          "Char the tortillas directly over a gas flame for authentic flavor.",
          "Make your own taco seasoning — it's fresher and has no additives.",
        ],
      },
      {
        id: "corn-burritos",
        title: "Burritos",
        description: "Oversized flour tortillas stuffed with rice, beans, corn, cheese, and your choice of protein.",
        image: "/images/recipes/corn-burritos.jpg",
        category: "Mexican",
        titleKey: "recipe.corn-burritos.title",
        descKey: "recipe.corn-burritos.desc",
        categoryKey: "rcat.mexican",
        cookingTime: "30 min",
        prepTime: "20 min",
        servings: 4,
        difficulty: "Medium",
        calories: 480,
        rating: 4.7,
        isVegetarian: false,
        isHealthy: false,
        isNew: false,
        isPopular: true,
        isChefSpecial: false,
        ingredients: [
          "4 large flour tortillas (12-inch)",
          "1 lb chicken breast, grilled and sliced",
          "1 cup Mexican rice (cooked)",
          "1 can (15 oz) black beans, drained",
          "1 cup corn kernels",
          "1 cup shredded cheddar cheese",
          "1/2 cup sour cream",
          "1/2 cup guacamole",
          "1 cup lettuce, shredded",
          "Salsa verde or roja",
        ],
        instructions: [
          "Prepare all fillings: cook the rice, grill and slice the chicken, warm the beans, and heat the corn.",
          "Warm each tortilla in a dry skillet or microwave for 15 seconds to make it pliable.",
          "Lay the tortilla flat. Layer the fillings in a line across the center: rice, beans, corn, chicken, cheese, lettuce, sour cream, and guacamole.",
          "Fold the bottom of the tortilla up over the fillings. Fold in the sides, then roll tightly from bottom to top.",
          "Heat a clean skillet over medium heat. Place the burrito seam-side down and cook for 2–3 minutes until golden and sealed.",
          "Slice in half diagonally and serve with salsa on the side.",
        ],
        nutrition: {
          protein: "35g",
          carbs: "52g",
          fat: "18g",
          fiber: "8g",
        },
        tips: [
          "Don't overfill — leave a 2-inch border around the edges for easy folding.",
          "Pressing the burrito in the skillet creates a crispy seal that holds everything together.",
          "Wrap in foil for a handheld meal on the go.",
        ],
      },
      {
        id: "corn-quesadilla",
        title: "Quesadilla",
        description: "Crispy tortillas filled with melted cheese, corn, peppers, and served with sour cream and salsa.",
        image: "/images/recipes/corn-quesadilla.jpg",
        category: "Mexican",
        titleKey: "recipe.corn-quesadilla.title",
        descKey: "recipe.corn-quesadilla.desc",
        categoryKey: "rcat.mexican",
        cookingTime: "15 min",
        prepTime: "10 min",
        servings: 4,
        difficulty: "Easy",
        calories: 380,
        rating: 4.8,
        isVegetarian: true,
        isHealthy: false,
        isNew: false,
        isPopular: true,
        isChefSpecial: false,
        ingredients: [
          "4 large flour tortillas",
          "2 cups shredded Oaxaca or Monterey Jack cheese",
          "1 cup corn kernels",
          "1/2 cup red bell pepper, diced",
          "1/4 cup green onions, sliced",
          "1 jalapeño, seeded and diced",
          "2 tablespoons butter",
          "Sour cream for serving",
          "Salsa for serving",
          "Guacamole for serving",
        ],
        instructions: [
          "Mix the shredded cheese with corn, bell pepper, green onions, and jalapeño in a bowl.",
          "Place a tortilla in a dry skillet over medium heat. Spread 1/4 of the cheese mixture on one half.",
          "Fold the tortilla in half and press down gently with a spatula.",
          "Cook for 2–3 minutes per side until the tortilla is golden and crispy and the cheese is fully melted.",
          "Remove from heat and let rest for 1 minute. Cut into 3 wedges.",
          "Repeat with remaining tortillas. Serve with sour cream, salsa, and guacamole.",
        ],
        nutrition: {
          protein: "18g",
          carbs: "32g",
          fat: "22g",
          fiber: "3g",
        },
        tips: [
          "Use low heat and be patient — high heat burns the tortilla before the cheese melts.",
          "Butter the outside of the tortilla for extra crispy results.",
          "Add leftover shredded chicken or carnitas for a heartier quesadilla.",
        ],
      },
      {
        id: "corn-nachos",
        title: "Nachos",
        description: "Loaded nachos with melted cheese, corn, jalapenos, black beans, and all the fixings.",
        image: "/images/recipes/corn-nachos.jpg",
        category: "Mexican",
        titleKey: "recipe.corn-nachos.title",
        descKey: "recipe.corn-nachos.desc",
        categoryKey: "rcat.mexican",
        cookingTime: "20 min",
        prepTime: "15 min",
        servings: 6,
        difficulty: "Easy",
        calories: 420,
        rating: 4.6,
        isVegetarian: true,
        isHealthy: false,
        isNew: false,
        isPopular: true,
        isChefSpecial: false,
        ingredients: [
          "1 large bag tortilla chips",
          "2 cups shredded cheddar cheese",
          "1 cup Monterey Jack cheese, shredded",
          "1 cup corn kernels",
          "1 can (15 oz) black beans, drained",
          "2 jalapeños, sliced",
          "1/2 cup pico de gallo",
          "1/4 cup sour cream",
          "1/4 cup guacamole",
          "Fresh cilantro for garnish",
          "Hot sauce to taste",
        ],
        instructions: [
          "Preheat oven to 400°F (200°C). Line a large baking sheet with parchment paper.",
          "Spread a single layer of tortilla chips on the baking sheet. Sprinkle with half the cheese.",
          "Add another layer of chips, then top with corn, black beans, jalapeños, and remaining cheese.",
          "Bake for 8–10 minutes until the cheese is fully melted and bubbly.",
          "Remove from oven and immediately top with pico de gallo, dollops of sour cream and guacamole.",
          "Garnish with fresh cilantro and hot sauce. Serve immediately while the cheese is still melty.",
        ],
        nutrition: {
          protein: "16g",
          carbs: "48g",
          fat: "22g",
          fiber: "8g",
        },
        tips: [
          "Layer the cheese between chips — not just on top — for maximum melt coverage.",
          "Don't overload with wet toppings before baking or the chips get soggy.",
          "Use a sheet pan, not a bowl, for even heat distribution.",
        ],
      },
      {
        id: "corn-salsa",
        title: "Salsa",
        description: "Fresh corn salsa with tomatoes, onion, cilantro, and serrano peppers. Perfect with chips.",
        image: "/images/recipes/corn-salsa.jpg",
        category: "Mexican",
        titleKey: "recipe.corn-salsa.title",
        descKey: "recipe.corn-salsa.desc",
        categoryKey: "rcat.mexican",
        cookingTime: "10 min",
        prepTime: "10 min",
        servings: 6,
        difficulty: "Easy",
        calories: 80,
        rating: 4.5,
        isVegetarian: true,
        isHealthy: true,
        isNew: true,
        isPopular: false,
        isChefSpecial: false,
        ingredients: [
          "3 cups corn kernels (fresh or thawed frozen)",
          "1 cup Roma tomatoes, diced",
          "1/2 cup red onion, finely diced",
          "1/4 cup fresh cilantro, chopped",
          "1 serrano pepper, seeded and minced",
          "2 tablespoons fresh lime juice",
          "1 tablespoon olive oil",
          "1/2 teaspoon cumin",
          "Salt to taste",
        ],
        instructions: [
          "If using fresh corn, blanch in boiling water for 2 minutes, then drain and cool.",
          "In a large bowl, combine the corn, tomatoes, red onion, cilantro, and serrano pepper.",
          "Drizzle with lime juice and olive oil. Add cumin and salt.",
          "Toss gently to combine all the ingredients.",
          "Let the salsa sit for 10 minutes at room temperature for the flavors to meld.",
          "Serve with tortilla chips or as a topping for tacos and grilled meats.",
        ],
        nutrition: {
          protein: "3g",
          carbs: "14g",
          fat: "3g",
          fiber: "2g",
        },
        tips: [
          "Char the corn in a dry skillet first for a smoky flavor.",
          "This salsa tastes even better the next day after the flavors have married.",
          "Add diced mango or pineapple for a tropical twist.",
        ],
      },
    ],
  },
  {
    id: "main-dishes",
    name: "Main Dishes",
    nameKey: "rcat.mainDishes",
    emoji: "\ud83c\udf55",
    recipes: [
      {
        id: "corn-pizza",
        title: "Corn Pizza",
        description: "Artisan pizza topped with sweet corn, mozzarella, basil, and a drizzle of truffle oil.",
        image: "/images/recipes/corn-pizza.jpg",
        category: "Main Dishes",
        titleKey: "recipe.corn-pizza.title",
        descKey: "recipe.corn-pizza.desc",
        categoryKey: "rcat.mainDishes",
        cookingTime: "25 min",
        prepTime: "15 min",
        servings: 4,
        difficulty: "Medium",
        calories: 450,
        rating: 4.7,
        isVegetarian: true,
        isHealthy: false,
        isNew: true,
        isPopular: false,
        isChefSpecial: true,
        ingredients: [
          "1 lb pizza dough (store-bought or homemade)",
          "1 cup pizza sauce",
          "2 cups fresh mozzarella, sliced",
          "1.5 cups corn kernels",
          "1/4 cup red onion, thinly sliced",
          "1/4 cup fresh basil leaves",
          "2 tablespoons truffle oil",
          "1/4 cup parmesan, grated",
          "Red pepper flakes (optional)",
          "Olive oil for drizzling",
        ],
        instructions: [
          "Preheat oven to 475°F (245°C) with a pizza stone or inverted baking sheet inside for 30 minutes.",
          "Stretch the dough on a floured surface to a 12-inch circle. Transfer to parchment paper.",
          "Spread the pizza sauce evenly over the dough, leaving a 1-inch border for the crust.",
          "Arrange the mozzarella slices over the sauce. Distribute the corn and red onion evenly.",
          "Drizzle with olive oil. Slide the pizza (on parchment) onto the hot stone.",
          "Bake for 12–15 minutes until the crust is golden and the cheese is bubbly with brown spots.",
          "Remove from oven. Top with fresh basil, grated parmesan, and a drizzle of truffle oil.",
          "Slice and serve immediately.",
        ],
        nutrition: {
          protein: "20g",
          carbs: "48g",
          fat: "22g",
          fiber: "3g",
        },
        tips: [
          "Preheat the oven with the stone inside for the crispiest crust.",
          "Pat the corn dry before topping to prevent a soggy pizza.",
          "Add the truffle oil after baking — heat destroys its delicate aroma.",
        ],
      },
      {
        id: "pasta-with-corn",
        title: "Pasta with Corn",
        description: "Creamy pasta with sweet corn, bacon, parmesan, and fresh cracked pepper.",
        image: "/images/recipes/pasta-with-corn.jpg",
        category: "Main Dishes",
        titleKey: "recipe.pasta-with-corn.title",
        descKey: "recipe.pasta-with-corn.desc",
        categoryKey: "rcat.mainDishes",
        cookingTime: "20 min",
        prepTime: "10 min",
        servings: 4,
        difficulty: "Easy",
        calories: 420,
        rating: 4.6,
        isVegetarian: false,
        isHealthy: false,
        isNew: false,
        isPopular: true,
        isChefSpecial: false,
        ingredients: [
          "12 oz penne or rigatoni pasta",
          "4 slices bacon, diced",
          "2 cups corn kernels",
          "2 cloves garlic, minced",
          "1 cup heavy cream",
          "1/2 cup pasta water (reserved)",
          "1 cup parmesan cheese, grated",
          "2 tablespoons butter",
          "Fresh basil, torn",
          "Freshly cracked black pepper",
          "Salt to taste",
        ],
        instructions: [
          "Cook the pasta in salted boiling water according to package directions. Reserve 1/2 cup pasta water before draining.",
          "While the pasta cooks, render the diced bacon in a large skillet over medium heat until crispy (5–6 minutes). Remove bacon, leave the fat.",
          "Add corn to the bacon fat and cook for 3–4 minutes until slightly charred. Add garlic and cook 1 minute.",
          "Pour in the heavy cream and bring to a gentle simmer. Cook for 3 minutes to slightly thicken.",
          "Add the drained pasta to the skillet. Toss with the cream sauce, adding pasta water as needed for consistency.",
          "Remove from heat. Stir in the butter and parmesan until melted and glossy.",
          "Season with salt and generous cracked pepper. Top with crispy bacon and torn basil.",
        ],
        nutrition: {
          protein: "18g",
          carbs: "52g",
          fat: "20g",
          fiber: "3g",
        },
        tips: [
          "Reserve pasta water — the starch helps the sauce cling to the pasta.",
          "Add the parmesan off the heat to prevent it from clumping.",
          "Use fresh corn cut from the cob for the sweetest results.",
        ],
      },
      {
        id: "corn-rice",
        title: "Corn Rice",
        description: "Fragrant rice pilaf studded with corn, peas, and herbs. A perfect side or light meal.",
        image: "/images/recipes/corn-rice.jpg",
        category: "Main Dishes",
        titleKey: "recipe.corn-rice.title",
        descKey: "recipe.corn-rice.desc",
        categoryKey: "rcat.mainDishes",
        cookingTime: "30 min",
        prepTime: "10 min",
        servings: 4,
        difficulty: "Easy",
        calories: 320,
        rating: 4.4,
        isVegetarian: true,
        isHealthy: true,
        isNew: false,
        isPopular: false,
        isChefSpecial: false,
        ingredients: [
          "1.5 cups long-grain white rice",
          "2 cups corn kernels",
          "1/2 cup green peas",
          "2.5 cups chicken or vegetable broth",
          "2 tablespoons butter",
          "1 small onion, diced",
          "2 cloves garlic, minced",
          "1/2 teaspoon cumin",
          "Salt and pepper to taste",
          "Fresh cilantro for garnish",
        ],
        instructions: [
          "Rinse the rice under cold water until the water runs clear. Drain well.",
          "Melt butter in a medium saucepan over medium heat. Sauté the onion for 3 minutes. Add garlic and cumin, cook 1 minute.",
          "Add the rice and stir for 2 minutes until the grains are lightly toasted and coated in butter.",
          "Pour in the broth. Add the corn and peas. Stir once, then bring to a boil.",
          "Reduce heat to low, cover tightly, and simmer for 18 minutes without lifting the lid.",
          "Remove from heat and let steam, covered, for 5 minutes. Fluff with a fork.",
          "Garnish with fresh cilantro and serve.",
        ],
        nutrition: {
          protein: "8g",
          carbs: "58g",
          fat: "6g",
          fiber: "4g",
        },
        tips: [
          "Toasting the rice in butter before adding liquid adds a nutty depth of flavor.",
          "Don't lift the lid while cooking — the steam is essential for fluffy rice.",
          "Substitute brown rice for a healthier option (add 10 minutes to cook time).",
        ],
      },
      {
        id: "chicken-and-corn",
        title: "Chicken & Corn",
        description: "Juicy grilled chicken served with roasted corn, chimichurri, and seasonal vegetables.",
        image: "/images/recipes/chicken-and-corn.jpg",
        category: "Main Dishes",
        titleKey: "recipe.chicken-and-corn.title",
        descKey: "recipe.chicken-and-corn.desc",
        categoryKey: "rcat.mainDishes",
        cookingTime: "35 min",
        prepTime: "20 min",
        servings: 4,
        difficulty: "Medium",
        calories: 420,
        rating: 4.8,
        isVegetarian: false,
        isHealthy: true,
        isNew: false,
        isPopular: true,
        isChefSpecial: false,
        ingredients: [
          "4 boneless chicken thighs",
          "4 ears of corn",
          "2 tablespoons olive oil",
          "1 teaspoon smoked paprika",
          "1 teaspoon garlic powder",
          "Salt and pepper",
          "1 cup chimichurri sauce (parsley, oregano, garlic, olive oil, red wine vinegar, red pepper flakes)",
          "Grilled vegetables (zucchini, bell pepper) for serving",
        ],
        instructions: [
          "Make the chimichurri: finely chop fresh parsley and oregano. Combine with minced garlic, olive oil, red wine vinegar, red pepper flakes, and salt. Set aside.",
          "Season chicken thighs with olive oil, smoked paprika, garlic powder, salt, and pepper.",
          "Preheat grill to medium-high. Grill the chicken for 6–7 minutes per side until internal temperature reaches 165°F.",
          "At the same time, grill the corn ears for 10–12 minutes, turning occasionally until charred on all sides.",
          "Let the chicken rest for 5 minutes, then slice.",
          "Serve the sliced chicken with grilled corn, drizzled generously with chimichurri, alongside grilled vegetables.",
        ],
        nutrition: {
          protein: "38g",
          carbs: "28g",
          fat: "20g",
          fiber: "4g",
        },
        tips: [
          "Marinate the chicken in chimichurri for 2 hours before grilling for deeper flavor.",
          "Use bone-in, skin-on thighs for juicier results.",
          "Make extra chimichurri — it keeps in the fridge for a week and goes with everything.",
        ],
      },
      {
        id: "corn-burgers",
        title: "Burgers",
        description: "Gourmet burgers with a corn patty, avocado, pickled onions, and chipotle aioli.",
        image: "/images/recipes/corn-burgers.jpg",
        category: "Main Dishes",
        titleKey: "recipe.corn-burgers.title",
        descKey: "recipe.corn-burgers.desc",
        categoryKey: "rcat.mainDishes",
        cookingTime: "25 min",
        prepTime: "20 min",
        servings: 4,
        difficulty: "Medium",
        calories: 520,
        rating: 4.7,
        isVegetarian: false,
        isHealthy: false,
        isNew: false,
        isPopular: true,
        isChefSpecial: false,
        ingredients: [
          "1.5 lbs ground beef (80/20)",
          "4 brioche buns, toasted",
          "2 cups corn kernels",
          "1 avocado, sliced",
          "1/2 cup pickled red onions",
          "4 leaves butter lettuce",
          "4 slices pepper jack cheese",
          "3 tablespoons chipotle mayo (mayo + adobo sauce)",
          "Salt, pepper, and garlic powder",
          "Butter for buns",
        ],
        instructions: [
          "Season the ground beef with salt, pepper, and garlic powder. Form into 4 equal patties slightly larger than the buns (they shrink while cooking).",
          "Heat a cast-iron skillet or grill to high heat. Sear the patties for 4 minutes on the first side without pressing.",
          "Flip the patties. Add a slice of pepper jack cheese to each. Cook for 3–4 more minutes for medium. Remove and rest 3 minutes.",
          "In the same skillet, char the corn kernels for 3 minutes. Set aside.",
          "Toast the buttered buns on the skillet for 1 minute until golden.",
          "Assemble: spread chipotle mayo on the bottom bun, add lettuce, patty with melted cheese, charred corn, avocado slices, and pickled onions. Top with the bun.",
        ],
        nutrition: {
          protein: "35g",
          carbs: "38g",
          fat: "28g",
          fiber: "5g",
        },
        tips: [
          "Don't press the patties while cooking — you'll squeeze out the juices.",
          "Make a thumbprint indent in the center of each patty to prevent puffing up.",
          "Quick-pickle red onions: slice thin, cover with equal parts vinegar and sugar for 30 minutes.",
        ],
      },
    ],
  },
  {
    id: "bakery",
    name: "Bakery",
    nameKey: "rcat.bakedGoods",
    emoji: "\ud83c\udf5e",
    recipes: [
      {
        id: "cornbread",
        title: "Cornbread",
        description: "Golden, moist cornbread with a slightly sweet flavor and crispy edges. A Southern classic.",
        image: "/images/recipes/cornbread.jpg",
        category: "Bakery",
        titleKey: "recipe.cornbread.title",
        descKey: "recipe.cornbread.desc",
        categoryKey: "rcat.bakedGoods",
        cookingTime: "35 min",
        prepTime: "10 min",
        servings: 8,
        difficulty: "Easy",
        calories: 220,
        rating: 4.8,
        isVegetarian: true,
        isHealthy: false,
        isNew: false,
        isPopular: true,
        isChefSpecial: true,
        ingredients: [
          "1 cup yellow cornmeal",
          "1 cup all-purpose flour",
          "1/4 cup granulated sugar",
          "1 tablespoon baking powder",
          "1/2 teaspoon salt",
          "1 cup buttermilk",
          "2 large eggs",
          "1/3 cup melted butter",
          "2 tablespoons butter for the skillet",
        ],
        instructions: [
          "Preheat oven to 400°F (200°C). Place a 10-inch cast-iron skillet with 2 tablespoons butter in the oven to heat.",
          "In a large bowl, whisk together the cornmeal, flour, sugar, baking powder, and salt.",
          "In a separate bowl, whisk the buttermilk, eggs, and melted butter together.",
          "Pour the wet ingredients into the dry ingredients. Stir until just combined — a few lumps are fine. Do not overmix.",
          "Carefully remove the hot skillet from the oven. The butter should be sizzling. Swirl to coat the pan.",
          "Pour the batter into the hot skillet. It should sizzle around the edges.",
          "Bake for 20–25 minutes until the top is golden and a toothpick inserted in the center comes out clean.",
          "Let cool in the skillet for 5 minutes before slicing. Serve warm with butter.",
        ],
        nutrition: {
          protein: "6g",
          carbs: "30g",
          fat: "10g",
          fiber: "2g",
        },
        tips: [
          "The hot skillet with sizzling butter creates the signature crispy bottom crust.",
          "Don't overmix the batter — it develops gluten and makes the cornbread tough.",
          "For sweeter cornbread, increase sugar to 1/3 cup.",
        ],
      },
      {
        id: "corn-muffins",
        title: "Corn Muffins",
        description: "Tender corn muffins with a golden crust, perfect for breakfast or as a side to soups and stews.",
        image: "/images/recipes/corn-muffins.jpg",
        category: "Bakery",
        titleKey: "recipe.corn-muffins.title",
        descKey: "recipe.corn-muffins.desc",
        categoryKey: "rcat.bakedGoods",
        cookingTime: "25 min",
        prepTime: "10 min",
        servings: 12,
        difficulty: "Easy",
        calories: 190,
        rating: 4.6,
        isVegetarian: true,
        isHealthy: false,
        isNew: false,
        isPopular: true,
        isChefSpecial: false,
        ingredients: [
          "1 cup yellow cornmeal",
          "1 cup all-purpose flour",
          "1/3 cup sugar",
          "1 tablespoon baking powder",
          "1/2 teaspoon salt",
          "1 cup buttermilk",
          "2 large eggs",
          "1/3 cup melted butter",
          "1 cup corn kernels (optional)",
        ],
        instructions: [
          "Preheat oven to 375°F (190°C). Line a 12-cup muffin tin with paper liners or grease well.",
          "In a large bowl, whisk together the cornmeal, flour, sugar, baking powder, and salt.",
          "In a separate bowl, whisk the buttermilk, eggs, and melted butter.",
          "Pour the wet ingredients into the dry. Stir until just combined. Fold in the corn kernels if using.",
          "Divide the batter evenly among the muffin cups, filling each about 3/4 full.",
          "Bake for 18–20 minutes until the tops are golden and a toothpick comes out clean.",
          "Cool in the pan for 5 minutes, then transfer to a wire rack.",
        ],
        nutrition: {
          protein: "5g",
          carbs: "26g",
          fat: "8g",
          fiber: "2g",
        },
        tips: [
          "For a honey-butter topping, brush melted butter mixed with honey on the warm muffins.",
          "Adding whole corn kernels gives a nice texture contrast.",
          "These freeze well — reheat in a 300°F oven for 10 minutes.",
        ],
      },
      {
        id: "corn-pancakes",
        title: "Corn Pancakes",
        description: "Fluffy pancakes made with fresh corn kernels, served with maple syrup and butter.",
        image: "/images/recipes/corn-pancakes.jpg",
        category: "Bakery",
        titleKey: "recipe.corn-pancakes.title",
        descKey: "recipe.corn-pancakes.desc",
        categoryKey: "rcat.bakedGoods",
        cookingTime: "20 min",
        prepTime: "10 min",
        servings: 4,
        difficulty: "Easy",
        calories: 280,
        rating: 4.5,
        isVegetarian: true,
        isHealthy: false,
        isNew: true,
        isPopular: false,
        isChefSpecial: false,
        ingredients: [
          "1 cup all-purpose flour",
          "1/2 cup cornmeal",
          "2 tablespoons sugar",
          "1.5 teaspoons baking powder",
          "1/2 teaspoon salt",
          "1 cup milk",
          "2 large eggs",
          "2 tablespoons melted butter",
          "1 cup corn kernels",
          "Butter for the griddle",
          "Maple syrup for serving",
        ],
        instructions: [
          "In a large bowl, whisk together the flour, cornmeal, sugar, baking powder, and salt.",
          "In a separate bowl, whisk the milk, eggs, and melted butter.",
          "Pour the wet ingredients into the dry and stir until just combined. Fold in the corn kernels.",
          "Heat a griddle or non-stick skillet over medium heat. Add a pat of butter.",
          "Pour 1/4 cup batter per pancake. Cook until bubbles form on the surface and the edges look set (about 2 minutes).",
          "Flip and cook for 1–2 more minutes until golden on the bottom.",
          "Serve warm with butter and maple syrup.",
        ],
        nutrition: {
          protein: "8g",
          carbs: "38g",
          fat: "12g",
          fiber: "3g",
        },
        tips: [
          "Don't overmix the batter — lumps are fine and keep the pancakes fluffy.",
          "For savory corn pancakes, omit the sugar and add cheese and scallions.",
          "Keep cooked pancakes warm in a 200°F oven while making the rest.",
        ],
      },
      {
        id: "corn-cake",
        title: "Corn Cake",
        description: "Moist and tender cake made with sweet corn, perfect with a dusting of powdered sugar.",
        image: "/images/recipes/corn-cake.jpg",
        category: "Bakery",
        titleKey: "recipe.corn-cake.title",
        descKey: "recipe.corn-cake.desc",
        categoryKey: "rcat.bakedGoods",
        cookingTime: "45 min",
        prepTime: "15 min",
        servings: 10,
        difficulty: "Medium",
        calories: 310,
        rating: 4.7,
        isVegetarian: true,
        isHealthy: false,
        isNew: false,
        isPopular: false,
        isChefSpecial: false,
        ingredients: [
          "1 cup corn kernels",
          "1/2 cup whole milk",
          "1.5 cups all-purpose flour",
          "1/2 cup cornmeal",
          "1 cup sugar",
          "1/2 cup butter, softened",
          "3 large eggs",
          "1.5 teaspoons baking powder",
          "1/2 teaspoon salt",
          "1 teaspoon vanilla extract",
          "Powdered sugar for dusting",
        ],
        instructions: [
          "Preheat oven to 350°F (175°C). Grease and flour a 9-inch round cake pan.",
          "Blend the corn kernels with the milk in a blender until smooth. Set aside.",
          "In a large bowl, cream the butter and sugar together until light and fluffy (3 minutes).",
          "Add the eggs one at a time, beating well after each. Add the vanilla.",
          "In a separate bowl, whisk the flour, cornmeal, baking powder, and salt.",
          "Alternate adding the dry ingredients and the corn-milk mixture to the butter mixture, beginning and ending with dry ingredients.",
          "Pour the batter into the prepared pan. Bake for 30–35 minutes until a toothpick comes out clean.",
          "Cool in the pan for 10 minutes, then turn out onto a wire rack. Dust with powdered sugar before serving.",
        ],
        nutrition: {
          protein: "6g",
          carbs: "42g",
          fat: "14g",
          fiber: "2g",
        },
        tips: [
          "Blending the corn with milk creates a smooth batter with natural corn sweetness.",
          "Don't overbake — check at 30 minutes to keep it moist.",
          "Serve with whipped cream and fresh berries for a dessert presentation.",
        ],
      },
    ],
  },
  {
    id: "desserts",
    name: "Desserts",
    nameKey: "rcat.desserts",
    emoji: "\ud83c\udf70",
    recipes: [
      {
        id: "corn-pudding",
        title: "Corn Pudding",
        description: "Creamy, custard-like pudding made with fresh corn, vanilla, and a hint of cinnamon.",
        image: "/images/recipes/corn-pudding.jpg",
        category: "Desserts",
        titleKey: "recipe.corn-pudding.title",
        descKey: "recipe.corn-pudding.desc",
        categoryKey: "rcat.desserts",
        cookingTime: "40 min",
        prepTime: "15 min",
        servings: 6,
        difficulty: "Medium",
        calories: 280,
        rating: 4.8,
        isVegetarian: true,
        isHealthy: false,
        isNew: false,
        isPopular: true,
        isChefSpecial: true,
        ingredients: [
          "3 cups corn kernels",
          "1 cup whole milk",
          "1 cup heavy cream",
          "3/4 cup sugar",
          "4 large eggs",
          "2 tablespoons butter, melted",
          "1 teaspoon vanilla extract",
          "1/2 teaspoon ground cinnamon",
          "1/4 teaspoon salt",
          "Whipped cream for serving",
        ],
        instructions: [
          "Preheat oven to 325°F (165°C). Butter a 2-quart baking dish.",
          "Blend the corn kernels with the milk and heavy cream in a blender until smooth.",
          "In a large bowl, whisk the sugar, eggs, melted butter, vanilla, cinnamon, and salt until well combined.",
          "Pour the corn mixture into the egg mixture and whisk until smooth.",
          "Strain the custard through a fine-mesh sieve into the prepared baking dish for a silky texture.",
          "Place the baking dish in a larger roasting pan. Pour hot water into the roasting pan until it reaches halfway up the sides of the dish.",
          "Bake for 45–50 minutes until the edges are set but the center still has a slight jiggle.",
          "Remove from the water bath and cool for 20 minutes. Serve warm or chilled with whipped cream.",
        ],
        nutrition: {
          protein: "8g",
          carbs: "38g",
          fat: "14g",
          fiber: "2g",
        },
        tips: [
          "Straining the custard removes corn hulls for a perfectly smooth pudding.",
          "The water bath (bain-marie) ensures gentle, even cooking without curdling.",
          "This pudding is delicious both warm and cold — try it both ways!",
        ],
      },
      {
        id: "sweet-corn-cake",
        title: "Sweet Corn Cake",
        description: "Dense, sweet cake with corn flavor, topped with whipped cream and caramel drizzle.",
        image: "/images/recipes/sweet-corn-cake.jpg",
        category: "Desserts",
        titleKey: "recipe.sweet-corn-cake.title",
        descKey: "recipe.sweet-corn-cake.desc",
        categoryKey: "rcat.desserts",
        cookingTime: "50 min",
        prepTime: "20 min",
        servings: 10,
        difficulty: "Hard",
        calories: 350,
        rating: 4.9,
        isVegetarian: true,
        isHealthy: false,
        isNew: false,
        isPopular: true,
        isChefSpecial: false,
        ingredients: [
          "1 cup masa harina",
          "1/2 cup all-purpose flour",
          "1 cup sugar",
          "1/2 cup butter, softened",
          "1/2 cup cream cheese, softened",
          "2 large eggs",
          "1 cup corn kernels",
          "1/2 cup whole milk",
          "1 teaspoon baking powder",
          "1/2 teaspoon salt",
          "1 teaspoon vanilla extract",
          "Whipped cream and caramel sauce for topping",
        ],
        instructions: [
          "Preheat oven to 325°F (165°C). Grease a 9-inch springform pan and line the bottom with parchment.",
          "Blend the corn kernels with the milk until smooth. Set aside.",
          "In a large bowl, cream the butter, cream cheese, and sugar until fluffy (4 minutes).",
          "Add the eggs one at a time, then the vanilla.",
          "In a separate bowl, whisk the masa harina, flour, baking powder, and salt.",
          "Alternate adding the dry ingredients and the corn-milk mixture to the butter mixture.",
          "Pour the batter into the prepared pan. Smooth the top.",
          "Bake for 45–50 minutes until golden on top and a toothpick comes out clean.",
          "Cool completely in the pan. Top with whipped cream and a generous caramel drizzle before serving.",
        ],
        nutrition: {
          protein: "7g",
          carbs: "45g",
          fat: "18g",
          fiber: "2g",
        },
        tips: [
          "Masa harina gives an authentic corn flavor and slightly gritty texture that's characteristic of this cake.",
          "The cream cheese keeps the cake incredibly moist for days.",
          "Dust with cinnamon sugar for an extra touch of warmth.",
        ],
      },
      {
        id: "caramel-corn",
        title: "Caramel Corn",
        description: "Crunchy popcorn coated in buttery caramel, a sweet treat that's impossible to resist.",
        image: "/images/recipes/caramel-corn.jpg",
        category: "Desserts",
        titleKey: "recipe.caramel-corn.title",
        descKey: "recipe.caramel-corn.desc",
        categoryKey: "rcat.desserts",
        cookingTime: "35 min",
        prepTime: "10 min",
        servings: 8,
        difficulty: "Medium",
        calories: 320,
        rating: 4.7,
        isVegetarian: true,
        isHealthy: false,
        isNew: false,
        isPopular: true,
        isChefSpecial: false,
        ingredients: [
          "1/2 cup popcorn kernels (about 12 cups popped)",
          "1 cup packed brown sugar",
          "1/4 cup light corn syrup",
          "1/2 cup unsalted butter",
          "1/2 teaspoon baking soda",
          "1/2 teaspoon vanilla extract",
          "1/4 teaspoon salt",
          "1 cup roasted peanuts (optional)",
        ],
        instructions: [
          "Preheat oven to 250°F (120°C). Line a large baking sheet with parchment paper.",
          "Pop the popcorn and remove any unpopped kernels. Place in a very large, greased bowl.",
          "In a medium saucepan, combine brown sugar, corn syrup, butter, and salt. Cook over medium heat, stirring until the butter melts.",
          "Stop stirring and let the mixture boil for 4 minutes.",
          "Remove from heat. Stir in the baking soda and vanilla — the mixture will foam up and become lighter in color.",
          "Pour the hot caramel over the popcorn (and peanuts if using). Toss with two greased spatulas to coat evenly.",
          "Spread onto the prepared baking sheet. Bake for 1 hour, stirring every 15 minutes.",
          "Let cool completely. Break into clusters and serve or store in an airtight container.",
        ],
        nutrition: {
          protein: "4g",
          carbs: "48g",
          fat: "14g",
          fiber: "3g",
        },
        tips: [
          "Grease your spatulas and bowl with cooking spray to prevent sticking.",
          "The caramel corn will crisp up significantly as it cools.",
          "Add a sprinkle of flaky sea salt on top for a salted caramel version.",
        ],
      },
    ],
  },
  {
    id: "drinks",
    name: "Drinks",
    nameKey: "rcat.beverages",
    emoji: "\ud83e\uddc3",
    recipes: [
      {
        id: "sweet-corn-juice",
        title: "Sweet Corn Juice",
        description: "Fresh pressed corn juice with a touch of honey and lime. Refreshing and nutritious.",
        image: "/images/recipes/sweet-corn-juice.jpg",
        category: "Drinks",
        titleKey: "recipe.sweet-corn-juice.title",
        descKey: "recipe.sweet-corn-juice.desc",
        categoryKey: "rcat.beverages",
        cookingTime: "10 min",
        prepTime: "10 min",
        servings: 2,
        difficulty: "Easy",
        calories: 120,
        rating: 4.5,
        isVegetarian: true,
        isHealthy: true,
        isNew: true,
        isPopular: false,
        isChefSpecial: false,
        ingredients: [
          "4 ears of corn, kernels cut from the cob",
          "2 cups water",
          "2 tablespoons honey",
          "1 tablespoon fresh lime juice",
          "Pinch of salt",
          "Ice cubes for serving",
          "Mint sprig for garnish",
        ],
        instructions: [
          "Cut the kernels from the cobs. Reserve the cobs.",
          "In a blender, combine the corn kernels, water, and reserved cobs. Blend on high for 2 minutes until very smooth.",
          "Strain the mixture through a fine-mesh sieve or cheesecloth into a pitcher, pressing to extract all the liquid.",
          "Stir in the honey, lime juice, and salt until dissolved.",
          "Taste and adjust sweetness. Chill in the refrigerator for 30 minutes.",
          "Serve over ice with a mint sprig garnish.",
        ],
        nutrition: {
          protein: "3g",
          carbs: "28g",
          fat: "1g",
          fiber: "3g",
        },
        tips: [
          "Use the freshest, sweetest corn available — it makes all the difference.",
          "The cobs add extra flavor and sweetness when blended — don't skip them.",
          "For a creamier version, add 1/4 cup coconut milk.",
        ],
      },
      {
        id: "corn-smoothie",
        title: "Corn Smoothie",
        description: "Creamy smoothie blended with sweet corn, banana, milk, and a dash of vanilla.",
        image: "/images/recipes/corn-smoothie.jpg",
        category: "Drinks",
        titleKey: "recipe.corn-smoothie.title",
        descKey: "recipe.corn-smoothie.desc",
        categoryKey: "rcat.beverages",
        cookingTime: "5 min",
        prepTime: "5 min",
        servings: 2,
        difficulty: "Easy",
        calories: 180,
        rating: 4.4,
        isVegetarian: true,
        isHealthy: true,
        isNew: true,
        isPopular: false,
        isChefSpecial: false,
        ingredients: [
          "1 cup corn kernels (cooked or thawed frozen)",
          "1 ripe banana",
          "1 cup whole milk (or oat milk)",
          "1/2 cup vanilla yogurt",
          "1 tablespoon honey",
          "1/2 teaspoon vanilla extract",
          "1/2 cup ice cubes",
          "Pinch of cinnamon",
        ],
        instructions: [
          "Add all ingredients to a blender in the order listed: corn, banana, milk, yogurt, honey, vanilla, ice, and cinnamon.",
          "Blend on high for 60–90 seconds until completely smooth and creamy.",
          "Taste and adjust sweetness with more honey if desired.",
          "Pour into glasses and serve immediately.",
          "Sprinkle a pinch of cinnamon on top for garnish.",
        ],
        nutrition: {
          protein: "8g",
          carbs: "34g",
          fat: "4g",
          fiber: "3g",
        },
        tips: [
          "Use frozen banana for a thicker, creamier smoothie.",
          "For a vegan version, use oat milk and coconut yogurt.",
          "Add a scoop of protein powder for a post-workout boost.",
        ],
      },
    ],
  },
];

export const allRecipes = recipeCategories.flatMap((cat) => cat.recipes);

export const filterCategories = [
  "All",
  "Street Corn",
  "Popcorn",
  "Salads",
  "Soups",
  "Mexican",
  "Main Dishes",
  "Bakery",
  "Desserts",
  "Drinks",
];

export const difficultyFilters = ["All", "Easy", "Medium", "Hard"];
export const timeFilters = ["All", "Under 15 min", "15-30 min", "30+ min"];
export const tagFilters = ["Popular", "New", "Vegetarian", "Healthy"];
